# 版本
edition = "bedrock"

# 种子
seed = ""

# 史莱姆区块颜色
slime_color = "#ffffff"

# 输出目录
output_dir = "chunks"

# 输出图片文件名
output_name = "{x1}_{z1}_{x2}_{z2}"

# 图片格式
format = "png"

# 进程数
# 小于或等于0相当于CPU核数
workers = 0

# 是否启用环模式 (true则忽略regions数组)
enable_ring = true

# 环数 (每象限n×n个区块，总4n²个区块)
# 1环 = 每象限1×1, 2环 = 每象限2×2, 3环 = 每象限3×3
ring_count = 3

# 原点坐标 (环的中心起点)
ring_origin = [0, 0]

# 环大小 (每个区块的边长)
ring_size = 512

# 要生成的区域列表
# 每个区域格式: [x1, z1, x2, z2]
regions = [
  # 第一象限 x+ z+
  [0, 0, 511, 511],        # 左下
  [0, 512, 511, 1023],     # 左上
  [512, 512, 1023, 1023],  # 右上
  [512, 0, 1023, 511],     # 右下
  
  # 第二象限 x- z+
  [-512, 0, -1, 511],      # 右下
  [-1024, 0, -513, 511],   # 左下
  [-1024, 512, -513, 1023], # 左上
  [-512, 512, -1, 1023],    # 右上
  
  # 第三象限 x- z-
  [-512, -512, -1, -1],       # 右上
  [-1024, -512, -513, -1],    # 左上
  [-1024, -1024, -513, -513], # 左下
  [-512, -1024, -1, -513],    # 右下
  
  # 第四象限 x+ z-
  [0, -512, 511, -1],       # 左上
  [512, -512, 1023, -1],    # 右上
  [512, -1024, 1023, -513], # 右下
  [0, -1024, 511, -513]     # 左下
]